### ISSUE TITLE
benchmark results

### ISSUE THREAD

**Issue by evelynmitchell** [cjm00/dedup#2]
`python3 benchrunner

Downloading test corpus...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  124M  100  124M    0     0  1956k      0  0:01:04  0:01:04 --:--:-- 2747k

Unpacking test corpus...

Concatenating files in to single blob...

/bin/sh: dedup: command not found

/bin/sh: dedup: command not found

/bin/sh: dedup: command not found

/bin/sh: dedup: command not found

sort | uniq: [19.610267162322998, 19.310322523117065, 19.74545121192932] mean: 19.555346965789795

dedup: [0.0023207664489746094, 0.0020852088928222656, 0.0018146038055419922] mean: 0.002073526382446289
`

**Comment by deepinthebuild** [comment]
Fixed in same update as #3, thanks for the bug report!
