### ISSUE TITLE
benchmark fails to run

### ISSUE THREAD

**Issue by evelynmitchell** [cjm00/dedup#3]
After running 'Cargo install' which places the dedup executable in ~/.cargo/bin/dedup the benchrunner fails to correctly set the path/current working directory.

FileNotFoundError: [Errno 2] No such file or directory: 'sort -u europarl.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'dedup europarl.txt'

**Comment by deepinthebuild** [comment]
The benchmark runner now handles paths correctly, thanks for the bug report!
